name: "Github Watcher Action"
description: "Run Github Watcher"

inputs:
  version:
    description: "Github Watcher version"
    required: true
    default: "0.5.0"
  config_path:
    description: "Path to config file"
    required: true
  env_variables:
    description: "Environment variables"
    required: false
  state_path:
    description: "Path to state directory, should be absolute and independent from the runner's workspace, otherwise cache will not work correctly"
    required: false
    default: "/tmp/github-watcher-action/state"
  env_path:
    description: "Path to env file, that will be used to pass env_variables to the container"
    required: false
    default: ".env"
  state_cache_prefix:
    description: "Cache prefix for state directory"
    required: false
    default: "github-watcher-state"

outputs:
  state_cache_key:
    description: "Cache key for state directory"
    value: ${{ inputs.state_cache_prefix }}-${{ github.run_id }}-${{ github.run_attempt }}

runs:
  using: "composite"
  steps:
    - name: Prepare env file
      shell: bash
      env:
        env_variables: ${{ inputs.env_variables }}
        env_path: ${{ inputs.env_path }}
      run: |
        mkdir -p $(dirname $env_path)
        echo "$env_variables" >> $env_path

    - name: Prepare state directory
      id: prepare-state-directory
      uses: actions/cache/restore@v4
      with:
        path: ${{ inputs.state_path }}
        # cache is immutable, so we need to create a new key for each run
        # https://github.com/actions/cache/blob/main/tips-and-workarounds.md#update-a-cache
        key: ${{ inputs.state_cache_prefix }}-${{ github.run_id }}-${{ github.run_attempt }}
        restore-keys: ${{ inputs.state_cache_prefix }}-
        enableCrossOsArchive: true

    - name: Create state directory if cache miss
      if: steps.prepare-state-directory.outputs.cache-hit != 'true'
      shell: bash
      env:
        state_path: ${{ inputs.state_path }}
      run: |
        mkdir -p $state_path

    - name: Run docker container
      shell: bash
      env:
        settings_path: ${{ github.action_path }}/settings.yaml
        config_path: ${{ github.workspace }}/${{ inputs.config_path }}
        state_path: ${{ inputs.state_path }}
        env_path: ${{ inputs.env_path }}
        version: ${{ inputs.version }}
      run: |
        docker run \
          --rm \
          --volume $settings_path:/settings.yaml \
          --volume $config_path:/config.yaml \
          --volume $state_path:/state \
          --env-file $env_path \
          --env GITHUB_WATCHER_SETTINGS_YAML=/settings.yaml \
          --user $UID:$GID \
          ghcr.io/ovsds/github-watcher:$version

    - name: Print state directory
      shell: bash
      env:
        state_path: ${{ inputs.state_path }}
      run: |
        find $state_path -ls

    - name: Save state directory
      if: success() || failure()
      uses: actions/cache/save@v4
      with:
        path: ${{ inputs.state_path }}
        key: ${{ inputs.state_cache_prefix }}-${{ github.run_id }}-${{ github.run_attempt }}

    - name: Cleanup state directory
      if: success() || failure()
      shell: bash
      env:
        state_path: ${{ inputs.state_path }}
      run: |
        rm -rf $state_path

    - name: Cleanup env file
      if: success() || failure()
      shell: bash
      env:
        env_path: ${{ inputs.env_path }}
      run: |
        rm $env_path

branding:
  icon: "message-circle"
  color: "blue"
