tasks:
  - id: example_task
    type: once_per_run
    triggers:
      - id: example_trigger
        type: github
        token_secret:
          type: env
          key: GITHUB_TOKEN
        owner: ovsds
        include_repos:
          - github-watcher-action
        subtriggers:
          - type: repository_issue_created
            exclude_author:
              - ovsds
          - type: repository_pr_created
            exclude_author:
              - ovsds
          - type: repository_failed_workflow_run
            exclude:
              - Check PR
    actions:
      - id: example_action
        type: telegram_webhook
        chat_id_secret:
          type: env
          key: TELEGRAM_CHAT_ID
        token_secret:
          type: env
          key: TELEGRAM_TOKEN
