name: Example workflow

concurrency:
  group: ${{ github.workflow }}

on:
  schedule:
    - cron: "* */1 * * *" # every hour
  workflow_dispatch:

jobs:
  run-github-watcher:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout config file
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          sparse-checkout: |
            example_config.yaml
          sparse-checkout-cone-mode: false

      - name: Run
        uses: ovsds/github-watcher-action@main
        with:
          config_path: example_config.yaml
          env_variables: |
            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
            TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}
            TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}
